name: Python Hata Kontrolü

on: [push]

jobs:
  test-et:
    runs-on: ubuntu-latest
    steps:
      - name: Kodu İndir
        uses: actions/checkout@v3

      - name: Python Kodunu Çalıştır
        run: python main.py
